#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UTSHelps.Droid.Resource", IsApplication=true)]

namespace UTSHelps.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int Text = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Text_Gray = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int blue = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int HELPS_logo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_create = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_save = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_copy_holo_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_cut_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_paste_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_search_holo_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int SignInBackground = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080011
			public const int adapterWorkshop = 2131230737;
			
			// aapt resource value: 0x7f080007
			public const int bookingdate = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int bookingsAdapter = 2131230726;
			
			// aapt resource value: 0x7f080012
			public const int colorWorkshop = 2131230738;
			
			// aapt resource value: 0x7f080008
			public const int date = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int dateNtime = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int day = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int detail_workshop = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int edit_toolbar = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int fragmentContainer = 2131230721;
			
			// aapt resource value: 0x7f08000f
			public const int location = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int locationName = 2131230736;
			
			// aapt resource value: 0x7f080005
			public const int loginButton = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int loginPassword = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int loginStudentId = 2131230723;
			
			// aapt resource value: 0x7f080016
			public const int lstCurrentBooking = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int lstPastBooking = 2131230743;
			
			// aapt resource value: 0x7f080015
			public const int lstWorkshop = 2131230741;
			
			// aapt resource value: 0x7f080000
			public const int main_content = 2131230720;
			
			// aapt resource value: 0x7f080019
			public const int menu_add = 2131230745;
			
			// aapt resource value: 0x7f080018
			public const int menu_bookings = 2131230744;
			
			// aapt resource value: 0x7f08001b
			public const int menu_edit = 2131230747;
			
			// aapt resource value: 0x7f08001d
			public const int menu_preferences = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public const int menu_save = 2131230748;
			
			// aapt resource value: 0x7f08001a
			public const int menu_settings = 2131230746;
			
			// aapt resource value: 0x7f080009
			public const int month = 2131230729;
			
			// aapt resource value: 0x7f08000e
			public const int time = 2131230734;
			
			// aapt resource value: 0x7f080014
			public const int toolbar = 2131230740;
			
			// aapt resource value: 0x7f08000b
			public const int txtWorkshop = 2131230731;
			
			// aapt resource value: 0x7f080013
			public const int workshopSets_text = 2131230739;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_Dashboard = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Adapter_Bookings = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Adapter_Workshops = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Fragment_MakeBooking = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Fragment_MyBookings = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Fragment_Settings = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int toolbar = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int edit_menus = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int top_menus = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
