#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("UTSHelps.Droid.Resource", IsApplication=true)]

namespace UTSHelps.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int Side_Bar = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Text = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Text_Gray = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int HELPS_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_create = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_content_save = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_copy_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_cut_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_menu_paste_holo_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_search_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int SignInBackground = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tick = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int userAddIcon = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080028
			public const int Rego2BestContactNo = 2131230760;
			
			// aapt resource value: 0x7f080018
			public const int adapterWorkshop = 2131230744;
			
			// aapt resource value: 0x7f080007
			public const int bookingdate = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int bookingsAdapter = 2131230726;
			
			// aapt resource value: 0x7f080019
			public const int colorWorkshop = 2131230745;
			
			// aapt resource value: 0x7f080008
			public const int date = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int dateNtime = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int day = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int detail_workshop = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int edit_toolbar = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int fragmentContainer = 2131230721;
			
			// aapt resource value: 0x7f08001f
			public const int imageView1 = 2131230751;
			
			// aapt resource value: 0x7f080023
			public const int linearLayout1 = 2131230755;
			
			// aapt resource value: 0x7f08000f
			public const int location = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int locationName = 2131230736;
			
			// aapt resource value: 0x7f080005
			public const int loginButton = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int loginPassword = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int loginStudentId = 2131230723;
			
			// aapt resource value: 0x7f08001d
			public const int lstCurrentBooking = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int lstPastBooking = 2131230750;
			
			// aapt resource value: 0x7f080037
			public const int lstSessions = 2131230775;
			
			// aapt resource value: 0x7f08001c
			public const int lstWorkshop = 2131230748;
			
			// aapt resource value: 0x7f080000
			public const int main_content = 2131230720;
			
			// aapt resource value: 0x7f080039
			public const int menu_add = 2131230777;
			
			// aapt resource value: 0x7f080038
			public const int menu_bookings = 2131230776;
			
			// aapt resource value: 0x7f08003b
			public const int menu_edit = 2131230779;
			
			// aapt resource value: 0x7f08003d
			public const int menu_preferences = 2131230781;
			
			// aapt resource value: 0x7f08003c
			public const int menu_save = 2131230780;
			
			// aapt resource value: 0x7f08003a
			public const int menu_settings = 2131230778;
			
			// aapt resource value: 0x7f080009
			public const int month = 2131230729;
			
			// aapt resource value: 0x7f080012
			public const int noOfSession = 2131230738;
			
			// aapt resource value: 0x7f080017
			public const int placesLeft = 2131230743;
			
			// aapt resource value: 0x7f080022
			public const int rego1StartButton = 2131230754;
			
			// aapt resource value: 0x7f08002a
			public const int rego2Birthdate = 2131230762;
			
			// aapt resource value: 0x7f080029
			public const int rego2Email = 2131230761;
			
			// aapt resource value: 0x7f080025
			public const int rego2PreferredFIrstName = 2131230757;
			
			// aapt resource value: 0x7f080024
			public const int rego2StudentName = 2131230756;
			
			// aapt resource value: 0x7f080026
			public const int rego2homePhone = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int rego2mobilePhone = 2131230759;
			
			// aapt resource value: 0x7f080030
			public const int rego3Course = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int rego3DegreeList = 2131230769;
			
			// aapt resource value: 0x7f08002f
			public const int rego3Faculty = 2131230767;
			
			// aapt resource value: 0x7f080032
			public const int rego3YearList = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int rego4AddBtn = 2131230771;
			
			// aapt resource value: 0x7f080035
			public const int rego5ContinueBtn = 2131230773;
			
			// aapt resource value: 0x7f08002c
			public const int rego5CountryList = 2131230764;
			
			// aapt resource value: 0x7f08002b
			public const int rego5GenderList = 2131230763;
			
			// aapt resource value: 0x7f08002d
			public const int rego5LanguageList = 2131230765;
			
			// aapt resource value: 0x7f080034
			public const int rego5NewBookingBtn = 2131230772;
			
			// aapt resource value: 0x7f08002e
			public const int rego5StatusList = 2131230766;
			
			// aapt resource value: 0x7f080014
			public const int sessionDate = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int sessionLocation = 2131230741;
			
			// aapt resource value: 0x7f080011
			public const int sessionName = 2131230737;
			
			// aapt resource value: 0x7f080016
			public const int sessionPlace = 2131230742;
			
			// aapt resource value: 0x7f080013
			public const int sessionTime = 2131230739;
			
			// aapt resource value: 0x7f080036
			public const int session_workshopName = 2131230774;
			
			// aapt resource value: 0x7f080020
			public const int textView1 = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int textView2 = 2131230753;
			
			// aapt resource value: 0x7f08000e
			public const int time = 2131230734;
			
			// aapt resource value: 0x7f08001b
			public const int toolbar = 2131230747;
			
			// aapt resource value: 0x7f08000b
			public const int txtWorkshop = 2131230731;
			
			// aapt resource value: 0x7f08001a
			public const int workshopSets_text = 2131230746;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_Dashboard = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Adapter_Bookings = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Adapter_Session = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Adapter_Workshops = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Fragment_MakeBooking = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Fragment_MyBookings = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Fragment_Registration1 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Fragment_Registration2 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Fragment_Registration3 = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Fragment_Registration4 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Fragment_Registration5 = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Fragment_Sessions = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Fragment_Settings = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int toolbar = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int edit_menus = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int top_menus = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
